### ISSUE TITLE
[Add/update member] Jacob-Junqi Tian

### ISSUE THREAD

**Issue by jacobthebanana** [ComplexData-MILA/complexdata-mila.github.io#1]
### Action

Add member

### Name

Jacob-Junqi Tian

### Role

Intern

### Status

Current Member

### Username

jacob-junqi.tian

### Semantic Scholar ID

2320260830

### Avatar

![Jacob- Mila- Cropped](https://github.com/user-attachments/assets/d8bc0383-7c4b-4dfc-9671-69d766ad0cfe)

### Advisor

Reihaneh Rabbany

### Date

May 2022

### Bio

Works on projects related to NLP, LLM, and Reasoning

### GitHub

https://github.com/jacobthebanana

### Scholar

https://scholar.google.com/citations?user=Bkl3SakAAAAJ

### Website

https://j7n.me/

### New Role

Associate Applied Machine Learning Specialist at Vector Institute

**Comment by RSTZZZ** [comment]
test
